### ISSUE TITLE
Add bigger font size and bold text to product prices

### ISSUE THREAD

**Issue by nikohoffren** [nikohoffren/hunajaholisti-homepage#10]
Make the font-size a bit larger and font-style bold on the product prices in Products.tsx file using Tailwind CSS classes.

**Comment by versacodes** [comment]
Hello. I would like to take on this issue.

**Comment by nikohoffren** [comment]
> Hello. I would like to take on this issue.

Sure, go ahead.

**Comment by versacodes** [comment]
There seems to be a weird bug in your project with tailwind. Arbitrary values don't work.
Like this:
`
"text-[2.5rem]"
`

Maybe a fresh install of tailwind will help? I'll try it.

**Comment by nikohoffren** [comment]
> There seems to be a weird bug in your project with tailwind. Arbitrary values don't work. Like this: `"text-[2.5rem]"`
> 
> Maybe a fresh install of tailwind will help? I'll try it.

Sorry, i forgot to mention in the instructions that you have to run `npx postcss src/index.css -o src/output.css` to apply the changes. After that it will work.

**Comment by versacodes** [comment]
I see. So you used the Tailwind CLI installation? Why not use the Framework install with Vite using React?

**Comment by nikohoffren** [comment]
> 

That's a good point, that would definitely be much more convenient solution that always use npx build. I might change that to make it easier in the future since im already using Vite.

**Comment by versacodes** [comment]
That's great. Btw, how big do you want it to be?

Like this?

![screenshot](https://github.com/nikohoffren/hunajaholisti-homepage/assets/114055827/73aeb587-d6f4-4bdb-9cd9-55cb32a09f4b)

**Comment by nikohoffren** [comment]
> That's great. Btw, how big do you want it to be?
> 
> Like this?
> 
> ![screenshot](https://user-images.githubusercontent.com/114055827/254486401-73aeb587-d6f4-4bdb-9cd9-55cb32a09f4b.jpg)

Maybe just a bit bigger font and it should be fine.

**Comment by versacodes** [comment]
> > That's great. Btw, how big do you want it to be?
> > Like this?
> > ![screenshot](https://user-images.githubusercontent.com/114055827/254486401-73aeb587-d6f4-4bdb-9cd9-55cb32a09f4b.jpg)
> 
> Maybe just a bit bigger font and it should be fine.

How about this? The middle one is the new one. So you can see the difference.

![screenshot](https://github.com/nikohoffren/hunajaholisti-homepage/assets/114055827/2252e70b-1679-4469-8b2b-854766ce9495)

**Comment by nikohoffren** [comment]
> > > That's great. Btw, how big do you want it to be?
> > > Like this?
> > > ![screenshot](https://user-images.githubusercontent.com/114055827/254486401-73aeb587-d6f4-4bdb-9cd9-55cb32a09f4b.jpg)
> > 
> > 
> > Maybe just a bit bigger font and it should be fine.
> 
> How about this? The middle one is the new one. So you can see the difference.
> 
> ![screenshot](https://user-images.githubusercontent.com/114055827/254488022-2252e70b-1679-4469-8b2b-854766ce9495.jpg)

That looks great.

**Comment by versacodes** [comment]
Done. I made a pull request.
