### ISSUE TITLE
Update footer links

### ISSUE THREAD

**Issue by nikohoffren** [nikohoffren/hunajaholisti-homepage#28]
Change `Honey receipts` and `Honey information` links in Footer.tsx to redirect user to different sites.

- `Honey receipts` href should be: https://www.valio.fi/reseptiryhmat/hunajareseptit/
- `Honey information` href should be: https://hunaja.net/hunajatietoa/hunaja/

**Comment by kabszac** [comment]
hi, can I be assigned  on this issue
