### ISSUE TITLE
Add a link to shopping cart for user to click when shopping cart is empty

### ISSUE THREAD

**Issue by nikohoffren** [nikohoffren/hunajaholisti-homepage#4]
Add a link to Cart.tsx page which should redirect user to Products.tsx page so they can start shopping. The link should appear only when the cart is empty.

**Comment by Joywin2412** [comment]
I'm ready to work on this issue. I'll use react-router-dom for this. Could you please assign this issue?

**Comment by nikohoffren** [comment]
> I'm ready to work on this issue. I'll use react-router-dom for this. Could you please assign this issue?

Sorry someone is already working on this issue. I have couple other issues open though.
